#!/bin/bash

python train_net.py --num-gpus 1 --config-file configs/rf_configs/aquarium-combined-fsod-zleg/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/the-dreidel-project-anzyr-fsod-unui/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/paper-parts-fsod-mpzq/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/x-ray-id-fsod-vgeh/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/gwhd2021-fsod-oxon/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/aerial-airport-fsod-ljmn/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/recode-fsod-flic/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/wb-prova-stqnm-fsod-zjxo/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/water-meter-jbktv-fsod-xoke/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/dentalai-i4clz-fsod-sgcd/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/trail-camera-fsod-najn/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/defect-detection-yjplx-fsod-jtua/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/wildfire-smoke-fsod-yden/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/actions-zzid2-fsod-onfc/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/all-elements-fsod-byio/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/orionproducts-fsod-vrmq/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/new-defects-in-wood-uewd1-fsod-wmwq/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/soda-bottles-fsod-ylap/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/flir-camera-objects-fsod-kqzb/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/lacrosse-object-detection-fsod-yorv/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
