#!/bin/bash

python train_net.py --num-gpus 1 --config-file configs/rf_configs/actions-zzid2-zb1hq-fsod-amih/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/aerial-airport-7ap9o-fsod-ddgc/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/all-elements-fsod-mebv/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/aquarium-combined-fsod-gjvb/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/defect-detection-yjplx-fxobh-fsod-amdi/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/dentalai-i4clz-fsod-fsuo/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/flir-camera-objects-fsod-tdqp/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/gwhd2021-fsod-atsv/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/lacrosse-object-detection-fsod-uxkt/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/new-defects-in-wood-uewd1-fsod-tffp/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/orionproducts-vtl2z-fsod-puhv/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/paper-parts-fsod-rmrg/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/recode-waste-czvmg-fsod-yxsw/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/soda-bottles-fsod-haga/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/the-dreidel-project-anzyr-fsod-zejm/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/trail-camera-fsod-egos/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/water-meter-jbktv-7vz5k-fsod-ftoz/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/wb-prova-stqnm-fsod-rbvg/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/wildfire-smoke-fsod-myxt/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/x-ray-id-zfisb-fsod-dyjv/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
