#!/bin/bash

python train_net.py --num-gpus 1 --config-file configs/rf_configs/actions-zzid2-zb1hq-fsod-ikol/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/gwhd2021-fsod-wmbp/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/lacrosse-object-detection-fsod-tvak/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/flir-camera-objects-fsod-jtjh/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/soda-bottles-fsod-zygh/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/new-defects-in-wood-uewd1-fsod-eivh/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/orionproducts-vtl2z-fsod-wcrf/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/all-elements-fsod-mnle/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/wildfire-smoke-fsod-pgox/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/defect-detection-yjplx-fxobh-fsod-hpfv/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/trail-camera-fsod-lyra/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/dentalai-i4clz-fsod-txmm/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/water-meter-jbktv-7vz5k-fsod-axdg/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/wb-prova-stqnm-fsod-tgki/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/recode-waste-czvmg-fsod-ttxl/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/aerial-airport-7ap9o-fsod-tahq/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/x-ray-id-zfisb-fsod-kxxa/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/paper-parts-fsod-tzbu/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/the-dreidel-project-anzyr-fsod-txpn/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
python train_net.py --num-gpus 1 --config-file configs/rf_configs/aquarium-combined-fsod-nlke/10_shots/zeroshot.yaml --pred_all_class --eval-only MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth OUTPUT_DIR_PREFIX /data3/anishmad/msr_thesis/rf_fsod_baselines/evalai_baselines/ 
